apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc-deployment
  labels:
    app: webmvc
spec:
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
        - name: webmvc
          image: jandocker511984/shoppingclient:latest
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value:  Development
            - name: APIUrl
              valueFrom:
                configMapKeyRef:
                  name:  webapi-configmap
                  key: webapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc-service
spec:
  type: NodePort
  selector:
    app: webmvc
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000
              
              